import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { readFile, mkdir } from 'node:fs/promises'
const base=process.env.APP_URL ?? 'http://127.0.0.1:5173'
const out=process.env.SHOT_DIR ?? '/tmp/firewatch-history-single'
await mkdir(out,{recursive:true})
const library=JSON.parse(await readFile(new URL('../public/data/historical-pilot.json', import.meta.url),'utf8'))
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL ?? 'chrome'})
try {
 const page=await browser.newPage({viewport:{width:1600,height:1100}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(`${base}/history`)
 await page.getByRole('heading',{name:'One fire. Its recorded history.'}).waitFor()
 await page.locator('.history-map path.leaflet-interactive').first().waitFor()
 assert.equal(await page.locator('.history-map').count(),1)
 assert.equal(await page.locator('.history-score,.history-matches').count(),0)
 // Both routes must use the same satellite source, attribution and map controls.
 const satelliteTiles = '.firewatch-map .leaflet-tile-pane img[src*="tiles.maps.eox.at"]'
 await page.locator(satelliteTiles).first().waitFor({state:'attached'})
 const attribution = await page.locator('.leaflet-control-attribution').innerText()
 assert.match(attribution,/Sentinel-2 cloudless 2020.*EOX/)
 assert.equal(await page.locator('.leaflet-bottom.leaflet-right .leaflet-control-zoom').count(),1)
 assert.equal(await page.locator('.leaflet-bottom.leaflet-right .leaflet-control-scale-line').count(),2)
 const home = await browser.newPage({viewport:{width:1600,height:1100}})
 home.on('pageerror',e=>errors.push(e.message))
 await home.goto(`${base}/`)
 await home.locator('.fire-canvas').waitFor()
 await home.getByRole('button',{name:'Satellite',exact:true}).click()
 await home.locator(satelliteTiles).first().waitFor({state:'attached'})
 assert.equal(await home.locator('.leaflet-control-attribution').innerText(),attribution)
 assert.equal(await home.locator('.leaflet-bottom.leaflet-right .leaflet-control-zoom').count(),1)
 assert.equal(await home.locator('.leaflet-bottom.leaflet-right .leaflet-control-scale-line').count(),2)
 assert.equal(await home.locator('.firewatch-map').count(),1)
 const zoomColors = async p => p.locator('.leaflet-control-zoom-in').evaluate(el => {
  const style = getComputedStyle(el)
  return {text:style.color,background:style.backgroundColor}
 })
 const historyZoomColors = await zoomColors(page)
 assert.deepEqual(historyZoomColors,await zoomColors(home))
 assert.equal(historyZoomColors.text,'rgb(0, 0, 0)')
 assert.equal(historyZoomColors.background,'rgb(255, 255, 255)')
 await home.close()
 await page.getByLabel('Basemap',{exact:true}).selectOption('topo')
 await page.locator('.leaflet-tile-pane img[src*="tile.opentopomap.org"]').first().waitFor({state:'attached'})
 assert.match(await page.locator('.leaflet-control-attribution').innerText(),/OpenTopoMap/)
 assert.doesNotMatch(await page.locator('.leaflet-control-attribution').innerText(),/EOX|Esri/)
 assert.equal(await page.locator('.leaflet-tile-pane > .leaflet-layer').count(),1)
 // A failed basemap must leave the historical overlays usable, then clear on switch.
 await page.route('https://tiles.maps.eox.at/**',r=>r.fulfill({status:503,body:'Unavailable'}))
 await page.getByLabel('Basemap',{exact:true}).selectOption('satellite')
 await page.locator('.history-tile-warning').waitFor()
 assert.ok(await page.locator('.history-map path.leaflet-interactive').count()>0)
 await page.getByLabel('Basemap',{exact:true}).selectOption('none')
 await page.locator('.history-tile-warning').waitFor({state:'hidden'})
 assert.equal(await page.locator('.leaflet-tile-pane > .leaflet-layer').count(),0)
 await page.unroute('https://tiles.maps.eox.at/**')

 const expected=['Creek','Kincade','County Rd 169','Cypress Creek','Bobcat'].map(name=>library.events.find(e=>e.name===name))
 assert.deepEqual(await page.locator('#reference-fire option').evaluateAll(xs=>xs.map(x=>x.value)),expected.map(e=>e.id))
 for(const e of expected) assert.match(await page.locator(`#reference-fire option[value="${e.id}"]`).innerText(),new RegExp(`${e.intervals.length} record`))
 assert.match(await page.locator('#reference-fire option:checked').innerText(), /Creek.*51 complete hours/)
 await page.locator('#reference-fire').selectOption('gofer:2020:Creek')
 await page.getByLabel('Basemap',{exact:true}).selectOption('none')
 const box=await page.locator('.history-map').boundingBox();assert.ok(box.width>1400&&box.height>=400 && box.y<450,JSON.stringify(box))
 await page.screenshot({path:`${out}/desktop.png`,fullPage:true})
 await page.getByRole('button',{name:'Focus map',exact:true}).click()
 assert.equal(await page.locator('.history-metrics').isVisible(),false)
 const focused=await page.locator('.history-map').boundingBox();assert.ok(focused.height>box.height)
 await page.getByRole('button',{name:'Show details',exact:true}).click()
 assert.equal(await page.locator('.history-metrics').isVisible(),true)
 await page.getByRole('button',{name:'Next record',exact:true}).click();assert.equal(await page.locator('#reference-hour').inputValue(),'1')
 await page.getByRole('button',{name:'▷ Play history'}).click()
 await page.waitForFunction(()=>document.querySelector('#reference-hour').value==='2')
 await page.getByRole('button',{name:'Ⅱ Pause'}).click()
 await page.getByLabel('Event timestamp',{exact:true}).fill('3')
 assert.equal(await page.locator('#reference-hour').inputValue(),'3')
 await page.locator('#reference-fire').selectOption('nifc:2026-TXTXF-000138')
 assert.equal(await page.locator('#reference-hour').inputValue(),'0')
 assert.equal(await page.getByRole('button',{name:'▷ Play history'}).isDisabled(),true)
 assert.equal(await page.locator('.history-snapshot-note').count(),1)
 assert.match(await page.locator('.history-area-stats').innerText(),/Unavailable/)
 await page.getByText('Inspect all source measurements',{exact:false}).click()
 assert.equal(await page.locator('.history-evidence tbody tr').count(),17)
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export record ↓'}).click()
 const file=await pending;await file.saveAs(`${out}/record.json`)
 const record=JSON.parse(await readFile(`${out}/record.json`,'utf8'));assert.equal(record.record.kind,'perimeter_snapshot');assert.equal(record.record.growth_ha,null);assert.equal('comparison' in record,false)
 await page.getByText('Inspect all source measurements',{exact:false}).click()
 await page.locator('#reference-fire').selectOption('gofer:2020:Creek')
 const zero=library.events.find(e=>e.name==='Creek').intervals.findIndex(r=>r.growth_ha===0)
 await page.locator('#reference-hour').selectOption(String(zero))
 assert.match(await page.locator('.history-area-stats').innerText(),/0 \/ 8/)
 await page.setViewportSize({width:390,height:844})
 await page.locator('.history-fire-card').scrollIntoViewIfNeeded()
 assert.ok(await page.evaluate(()=>document.querySelector('.history-page').scrollWidth<=innerWidth))
 await page.getByRole('button',{name:'Fit extent',exact:true}).click()
 await page.locator('.history-map').scrollIntoViewIfNeeded()
 await page.screenshot({path:`${out}/mobile.png`,fullPage:true})
 const failure=await browser.newPage();await failure.route('**/data/historical-pilot.json',r=>r.fulfill({status:503,body:'Unavailable'}));await failure.goto(`${base}/history`);await failure.getByRole('heading',{name:'Library unavailable'}).waitFor()
 assert.deepEqual(errors,[])
 console.log(JSON.stringify({result:'passed',options:expected.map(e=>[e.name,e.intervals.length]),desktopMap:box,checks:['shared satellite source and attribution','shared zoom/scale controls','basemap switching','tile failure preserves geometry','single map','sorted options and counts','playback','timeline','snapshot null growth','export','source evidence','zero growth','mobile overflow','load error'],screenshots:out}))
} finally {await browser.close()}
